#Install Prerequisites
- name: Update and Upgrade
  shell: sudo apt-get autoremove -y && sudo apt-get update -y && sudo apt-get upgrade -y

- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - python3-setuptools
      - lsb-release
      - gnupg
    state: latest
    update_cache: true

#Install Docker
- name: Add docker GDG apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository 
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    filename: docker

- name: update and upgrade
  shell: sudo apt-get update -y && sudo apt-get upgrade -y

- name: Install Docker Module for Python
  pip:
    name: 
      - docker
      - docker-compose

- name: Install Docker
  apt:
    name:
      - docker
      - docker.io
      - docker-registry
      - docker-compose-plugin
    state: latest
    update_cache: true



