- name: Copy Dockerfile
  copy:
    src: ~/devOps/Docker/elk_stack/DK/kibana/
    dest: /home/ubuntu/kibana/
    owner: root
    group: root
    mode: '0644'
    backup: no

- name: kibana deploy
  shell: |
    cd kibana
    sudo docker-compose up -d

  
